# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ML in PL Conference 2023
email: contact@conference.mlinpl.org
event-date: "2023-10-26T00:00:00"
countdown-date: "2023-10-26T00:00:00"
location: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2443.139924136593!2d21.027710165797096!3d52.24084207976233!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x471ecc5bae6f67c7%3A0x2fc064465f3234db!2sPlanetarium%20Centrum%20Nauki%20Kopernik!5e0!3m2!1sen!2spl!4v1678213067112!5m2!1sen!2spl
description: >-
  ML in PL Conference 2023 is an event focused on the best of Machine Learning both in academia and in business.
main-image: images/mlinpl-conference-2023-logo-black.png
twitter-username: "@MLinPL"
baseurl: "/www-dev" # the subpath of your site, e.g. /blog
url: "https://mlinpl.github.io/www-dev/" # the base hostname & protocol for your site, e.g. http://example.com

logo: <span class="logo"><span class="main-name">MLSS<span class="superscript">S</span></span> <span class="sub-name">2023</span></span>
inline-logo: <span class="logo"><span class="main-name">MLSS<span class="superscript">S</span></span> <span class="sub-name">2023</span></span>

# Build settings
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Color settings
color:
  main: "#E7322A"
  main-gradient: "#E7322A, #FF00FF"
  background: "#FFFFFF"

# Footer settings
footer: ML in PL Association

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/company/mlinpl
  - title: facebook
    url: https://www.facebook.com/MLinPL
  - title: twitter
    url: https://twitter.com/mlinpl
  - title: youtube
    url: https://www.youtube.com/channel/UCmXKn-Xeq1ZTAQBTwsYw4AA

# Build settings
markdown: kramdown
permalink: pretty

sass:
  style: compressed # possible values: nested expanded compact compressed
